spring.application.name=cbank-atx


# Connexion MongoDB Atlas
spring.mongodb.uri=mongodb+srv://root:root@cluster0.pxdrhrn.mongodb.net/cbank_atx

spring.ldap.urls=ldap://ldap-server:389
spring.ldap.base=dc=cbank,dc=cm
spring.ldap.username=cn=admin,dc=cbank,dc=cm
spring.ldap.password=ldap_admin_password
spring.mongodb.database=cbank_atx

# Logs MongoDB
logging.level.org.springframework.data.mongodb=DEBUG


# JWT Configuration  ? AJOUTE CES 2 LIGNES !
jwt.secret=cbank_atx_secret_key_2026_very_long_and_secure_key
jwt.expiration=86400000



# Port
server.port=8080