spring.application.name=cbank-atx

# Connexion MongoDB Atlas
spring.mongodb.uri=mongodb+srv://root:root@cluster0.pxdrhrn.mongodb.net/cbank_atx

spring.mongodb.database=cbank_atx

# Logs MongoDB
logging.level.org.springframework.data.mongodb=DEBUG

# Port
server.port=8080