# Application
spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

# MongoDB
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DATABASE}

# LDAP
spring.ldap.urls=${LDAP_URLS}
spring.ldap.base=${LDAP_BASE}
spring.ldap.username=${LDAP_USERNAME}
spring.ldap.password=${LDAP_PASSWORD}

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST}
spring.mail.properties.mail.smtp.ssl.protocols=${MAIL_SSL_PROTOCOLS}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Logs
logging.level.org.springframework.data.mongodb=DEBUG